# Generated by Django 3.0.4 on 2020-03-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManuAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('nodeName', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='SideMenu',
            new_name='SideMenuNode',
        ),
        migrations.RenameField(
            model_name='sidemenunode',
            old_name='json',
            new_name='type',
        ),
    ]
