# Generated by Django 3.0.4 on 2020-03-22 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0002_auto_20200322_2241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SideMenuNode',
            new_name='Side_Menu_Node',
        ),
        migrations.RenameModel(
            old_name='UserManuAccess',
            new_name='User_Menu_Access',
        ),
    ]
